### PR TITLE
WorkflowsService doesn't respect verify_ssl=False

### PR DESCRIPTION
**Pull request by jplikesbikes**

### CODE REVIEW

**Comment by jplikesbikes** [comment]
Since the major rewrite for v5 I'm not sure what needs to be done to pass ci. This is a one line change if someone with more knowledge of the system just wants to do it or walk me through it, either would be appreciated. Thanks

**Comment by samj1912** [comment]
@jplikesbikes you will need to change https://github.com/argoproj-labs/hera/blob/main/scripts/service.py#L403 and run `make codegen`

**Review by samj1912 — APPROVED** [review]

**Comment by KathrynFowler91** [comment]
Is it possible to add the same change to token and namespace also so that they also respect the `global_config`?

**Comment by samj1912** [comment]
@KathrynFowler91 those properties should work. Do you have a reproducible example?

**Comment by KathrynFowler91** [comment]
"""python
from hera.workflows import WorkflowsService
from hera.shared import global_config

from omegaconf import OmegaConf

from src.utils.hera_utils import get_token  # create token


app_settings = OmegaConf.load("app_settings.yaml")

global_config.namespace = app_settings.argoNamespace
global_config.service_account_name = app_settings.argoServiceAccountName
global_config.host = app_settings.argoHost
global_config.token = get_token()
global_config.verify_ssl = True
list_templates = WorkflowsService().list_workflow_templates()
print(list_templates)
"""

The error gives: `TypeError: WorkflowsService.list_workflow_templates() missing 1 required positional argument: 'namespace'`

**Comment by samj1912** [comment]
Ah, that seems to be an issue with the generated methods instead of the class itself. Can you please create an enhancement request for this?

**Comment by KathrynFowler91** [comment]
Will do. Thank you for the quick response.

**Pull request merged**
