### PR TITLE
Add Hera logo to README

### LINKED ISSUE #1003: Help needed: logo for Hera! 🚀
As Hera's popularity gains, and with features like the Hera Runner and Pydantic integration, it is becoming a project in its own right - building on, but distinct from, the core offering of Argo (Workflows). We thought it would be cool for Hera to have a mascot/logo as a visual to use throughout documentation, presentations and more!

We'd love to hear any ideas from the community, and if you want to share design ideas in this thread, please do! 

A logo for Hera could incorporate aspects and imagery related to -
* [Python](https://www.python.org/community/logos/)
* [Argo, the project](https://argoproj.github.io/)
* [Argo, the ship](https://en.wikipedia.org/wiki/Argo)
* Ancient Greek civilisation and mythology, in particular [Hera](https://en.wikipedia.org/wiki/Hera)

Or try something entirely different!

Once we have some designs we'll arrange a vote!

### PR DESCRIPTION
**Pull request by elliotgunton**
**Pull Request Checklist**
- [x] Closes #1003 

As we didn't have much activity in the issue for actual graphics, credit to @flaviuvadan who generated some logos using AI. 

I traced the logo to create a vector image. V1 is a bit rough and ready, I haven't measured anything for the hexagon to be exact but looks alright for now.

### CODE REVIEW

**Comment by elliotgunton** [comment]
I'd like approval from both @flaviuvadan and @samj1912 for this one as it's a brand new thing for Hera

**Review by flaviuvadan — COMMENTED** [review]
Reminder to upload the fixed logo with the bottom right edge straightened

**Comment by elliotgunton** [comment]
Docs page working now after some messing around

image

**Review by flaviuvadan — APPROVED** [review]

**Review by samj1912 — APPROVED** [review]
Lgtm. Would be nice to align the logo colors and docs colors, but we can do that in a subsequent PR

**Pull request merged**
