### PR TITLE
Add new ml pipeline example using spacy in use-cases folder

### PR DESCRIPTION
**Pull request by paravatha**
**Pull Request Checklist**
- [ ] Fixes #
- [ ] Tests added
- [x] Documentation/examples added
- [ ] [Good commit messages](https://cbea.ms/git-commit/) and/or PR title

**Description of PR**

Adding a new ML Pipeline example using spaCy english model https://spacy.io/models/en#en_core_web_lg
This relatively simple model inference pipeline performs NER task with below steps
1. data-prep
2. inference

### CODE REVIEW

**Review by flaviuvadan — COMMENTED** [review]
This looks awesome @paravatha! Any chance you are open to adding some inline documentation to the Python scripts? I am thinking a light module docstring that explains what the example is about + the use of spacy

**Review by elliotgunton — COMMENTED** [review]
Looks good! Just some housekeeping to tidy up 🚀

**Comment by paravatha** [comment]
@elliotgunton @flaviuvadan thanks for the quick response :-). 
I will make the changes in tomorrow or Friday

**Comment by paravatha** [comment]
> This looks awesome @paravatha! Any chance you are open to adding some inline documentation to the Python scripts? I am thinking a light module docstring that explains what the example is about + the use of spacy

Hi @flaviuvadan just to clarify, add docstring at the function level? and convert comments like [this](https://github.com/paravatha/paravatha-argo-workflows-hera/blob/f466955e48b03ab7544bfe9973394633d58f0bcd/examples/workflows/use-cases/ml_infer_pipeline_spacy.py#L79) and [this](https://github.com/paravatha/paravatha-argo-workflows-hera/blob/f466955e48b03ab7544bfe9973394633d58f0bcd/examples/workflows/use-cases/ml_infer_pipeline_spacy.py#L65) to docstrings?

Also, do you have any examples I can follow?

**Comment by paravatha** [comment]
@elliotgunton made changes as per your suggestions, please take a look!

**Comment by flaviuvadan** [comment]
Looks great @paravatha! I think a `make format` is needed to make CI pass. I will approve after!

**Comment by paravatha** [comment]
> Looks great @paravatha! I think a `make format` is needed to make CI pass. I will approve after!

should be good now @flaviuvadan

**Review by flaviuvadan — APPROVED** [review]
Thanks so much for the awesome example @paravatha! 🚀

**Comment by flaviuvadan** [comment]
@elliotgunton feel free to merge after your review / approval

**Pull request merged**
