### PR TITLE
Set status=None if any status field is None

### PR DESCRIPTION
**Pull request by iameskild**
**Pull Request Checklist**
- [x] Fixes # Related to #679
- [ ] Tests added
- [ ] Documentation/examples added
- [x] [Good commit messages](https://cbea.ms/git-commit/) and/or PR title

**Description of PR**

I kept running into the following error message when I would try to update my CronWorkflow. 

```py
pydantic.error_wrappers.ValidationError: 2 validation errors for CronWorkflow
status -> active
  none is not an allowed value (type=type_error.none.not_allowed)
status -> lastScheduledTime
  none is not an allowed value (type=type_error.none.not_allowed)
```

Unfortunately this error would only appear if at least workflow has been created. Comparing the two models, `WorkflowStatus`  `CronWorkflowStatus` in v1alpha1.py, it seems that the former has all of it's fields set to optional and it makes sense that the same should apply to `CronWorkflowStatus`; this is what this PR does. 

With this fix, I was able to update my CronWorkflows regardless of the current status.

### CODE REVIEW

**Comment by elliotgunton** [comment]
This would be changing the auto-generated classes so doesn't look like the right solution here. I think we might need to change the `and`s to `or`s in [scripts/service.py#L193](https://github.com/argoproj-labs/hera/blob/2eb239e6c3af72e3726528e8123139116c98a0d3/scripts/service.py#L193) @flaviuvadan?

**Comment by iameskild** [comment]
@elliotgunton that would make more sense. I just tested this for CronWorkflow and it seems to work. I just made that update to this PR.

**Comment by elliotgunton** [comment]
Hey @iameskild - you'll need to change the specific line in main/scripts/service.py to `or`s and then run `make codegen` (and commit) as the code you've changed is generated from the script so is currently failing CI/CD because of the diff

**Review by elliotgunton — COMMENTED** [review]
LGTM but would like @flaviuvadan to also take a look

**Review by flaviuvadan — APPROVED** [review]
Thank you for the fix @iameskild! 🎖️ LGTM

**Review by elliotgunton — APPROVED** [review]

**Pull request merged**
