### PR TITLE
Add argo lint on examples directory

### PR DESCRIPTION
**Pull request by jeongukjae**
**Pull Request Checklist**
- [ ] ~~Fixes~~ #1163 (not fixing, need to more work to fix actual lint problems)
- [ ] ~~Tests added~~ not needed here
- [ ] ~~Documentation/examples added~~ not needed here
- [x] [Good commit messages](https://cbea.ms/git-commit/) and/or PR title

**Description of PR**

This PR adds `make lint-argo` command to start work on issue #1163 
I will create additional fixes after this PR.

\+ Since, the actual lint errors are not addressed yet, I didn't add it to CI checks or Contributing docs.

### CODE REVIEW

**Comment by sambhav** [comment]
@jeongukjae can you add it to the CI now?

**Comment by jeongukjae** [comment]
@sambhav not yet :( currently I see 55 lint errors if I run `make lint-argo` in main branch.

**Comment by sambhav** [comment]
@jeongukjae can we run it but not fail on it?

**Comment by jeongukjae** [comment]
fyi, there are three kind of errors,

- minor manifest errors that I can fix (missing entrypoint, parameter, artifacts, ...)
- errors those need workflow template in the test cluster, and I can also fix, but need some time to set up
- errors caused by the syntaxes those are introduced in Argo Workflow 3.6 (currently, we use 3.5 in Makefile, so this will be fixed after https://github.com/argoproj-labs/hera/issues/1215)

so, how about

1. fixing first two issues in the following PRs,
2. and upgrading the Argo Workflow version in hera repo to 3.6
3. then adding this to CI?

if there's no strong reason to add this now?

through this, I will assign myself to the issue (https://github.com/argoproj-labs/hera/issues/1163), and fix this.

cc @elliotgunton

**Comment by elliotgunton** [comment]
Yeah, having tried a plain `argo lint examples` before, I don't think we should try to lint the folder wholesale (due to errors like multiple templates with the same name, plus (workflow)templaterefs.

**Comment by jeongukjae** [comment]
@elliotgunton makes sense.
How about limiting directories like this? (I added one another commit)

Then remained issues are as follows:
```
examples/workflows/experimental/new-dag-decorator-artifacts.yaml:
   ✖ in "my-workflow-" (Workflow): rpc error: code = Unknown desc = templates.worker inputs.artifacts.artifact_a was not supplied

examples/workflows/experimental/new-dag-decorator-inner-dag.yaml:
   ✖ in "my-workflow-" (Workflow): rpc error: code = Unknown desc = templates.outer-dag inputs.parameters.value_a was not supplied

examples/workflows/experimental/new-dag-decorator-params.yaml:
   ✖ in "my-workflow-" (Workflow): rpc error: code = Unknown desc = templates.worker inputs.parameters.value_b was not supplied

examples/workflows/experimental/new-decorators-auto-template-refs.yaml:
   ✖ in "my-workflow-" (Workflow): rpc error: code = Unknown desc = templates.worker inputs.parameters.value_b was not supplied

examples/workflows/experimental/new-steps-decorator-with-parallel-steps.yaml:
   ✖ in "my-workflow-" (Workflow): rpc error: code = Unknown desc = templates.worker inputs.parameters.value_b was not supplied

examples/workflows/experimental/script-annotations-artifact-custom-volume.yaml:
   ✖ in "test-output-annotations-" (Workflow): rpc error: code = Unknown desc = templates.my-steps.steps[3].use-artifact-existing-vol templates.use-artifact-existing-vol inputs.artifacts.successor_in was not supplied

examples/workflows/experimental/script-runner-io.yaml:
   ✖ in "pydantic-io-" (Workflow): rpc error: code = Unknown desc = spec.entrypoint is required

examples/workflows/experimental/template-sets.yaml:
   ✖ in "my-workflow" (Workflow): rpc error: code = Unknown desc = spec.entrypoint is required

examples/workflows/steps/steps-types.yaml:
   ✖ in "steps-" (Workflow): rpc error: code = Unknown desc = templates.hello-hello-hello.steps[3].name 'list-of-step-1' is not unique
```

I think those can be fixed.

**Comment by elliotgunton** [comment]
I'm closing this PR as I think it would be better to use the Hera API with tests, which was my original intention/idea to match the [API usage to create](https://github.com/argoproj-labs/hera/blob/f8550f01ea6dfb5a00957a75e74b2ecfb8ffc9e9/tests/submissions/test_hello_world.py#L34) workflows (although this wasn't clear from the original issue, I've added a note there). We can then use `xfail` for any that don't work in a similar way to the YAML [roundtrip tests](https://github.com/argoproj-labs/hera/blob/f8550f01ea6dfb5a00957a75e74b2ecfb8ffc9e9/tests/test_remaining_examples.py#L19), and it will be generally more maintainable.

**Pull request closed without merging**
